[package]
name = "libvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
libc = "0.2.153"
log = "0.4.21"
thiserror = "1.0.57"
virt = "0.3.1"
